repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.660
    hooks:
      - id: mypy
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
